version: '3.5'

services: 
 redis:
    container_name: redis1
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data


 mongo:
    image: mongo:latest
    container_name: mongoDB
    # restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/monodb:/data 
  
 neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: myneo
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/root
      NEO4J_dbms_logs_debug_level: DEBUG

#  neo4j:
#     image: neo4j:latest
#     hostname: neo4j
#     container_name: myneo
#     ports:
#       - "7474:7474"
#       - "7687:7687"
#     volumes:
#        - ./data:/var/lib/neo4j/data
#        - ./logs:/var/lib/neo4j/logs
#        - ./conf:/var/lib/neo4j/conf
#        - ./mnt:/var/lib/neo4j/import
#        - ./plugins:/var/lib/neo4j/plugins

#     environment:
#       - NEO4J_AUTH=neo4j/root


 elasticsearch:
    image: elasticsearch:8.4.2
    container_name: elasticsearch
    networks:
      elastic:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./tmp/elasticsearch:/usr/share/elasticsearch/data  
  
  
 postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: studentsDB
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    # restart: always

networks:
  elastic:
    driver: bridge